$(document).ready(function() {
	$('#loader').hide();
	
<!-- ----- BEDROOM ----- !-->
  $("#bed").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/bed.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/bed.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#cat").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/cat.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/cat.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#closet").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/closet.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/closet.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#doorKnob").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/doorKnob.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/doorKnob.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#sTableD").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/drawer.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/drawer.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#dresser").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/dresser.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/dresser.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#handle").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/handle.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/handle.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#pillow").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/pillow.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/pillow.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#sTable").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/sideTable.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/sideTable.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});

<!-- ----- EXTRA ROOM ----- !-->
	$("#railing").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/railing.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/railing.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#window").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/window.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/window.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#plant").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/plant.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/plant.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});

<!-- ----- BATHROOM ----- !-->
	$("#tub").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/bathtub.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/bathtub.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#drain").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/drain.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/drain.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#faucet").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/faucet.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/faucet.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#mirror").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/mirror.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/mirror.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#shower").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/shower.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/shower.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#showerHead").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/showerHead.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/showerHead.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#sink").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/sink.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/sink.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#toilet").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/toilet.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/toilet.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
<!-- ----- LIVING ROOM ----- !-->
	$("#calendar").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/calendar.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/calendar.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#clock").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/clock.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/clock.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#couch").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/couch.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/couch.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#cushion").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/cushion.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/cushion.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#dog").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/dog.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/dog.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#lamp").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/lamp.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/lamp.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#picture").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/picture.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/picture.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#socket").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/socket.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/socket.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#stairs").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/stairs.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/stairs.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
<!-- ----- KITCHEN/ENTRY ----- !-->
	$("#cabinets").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/cabinets.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/cabinets.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#chairs").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/chairs.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/chairs.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#coatRack").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/coatRack.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/coatRack.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#counter").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/counter.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/counter.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#door").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/door.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/door.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#freezer").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/freezer.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/freezer.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#fridge").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/fridge.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body")
	$("<audio></audio>").attr({ 
		'src':'audio/fridge.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	;});
	
	$("#jacket").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/jacket.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/jacket.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#mailSlot").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/mailSlot.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/mailSlot.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#oven").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/oven.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/oven.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#peepHole").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/peepHole.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/peepHole.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#stove").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/stove.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/stove.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
	
	$("#table").click(function(){
	$("<audio></audio>").attr({ 
		'src':'audio/table.mp3', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	$("<audio></audio>").attr({ 
		'src':'audio/table.ogg', 
		'volume':1,
		'autoplay':'autoplay'
	}).appendTo("body");
	});
});